### PR TITLE
Fix page/post count bug

### LINKED ISSUE #194: [Bug]: Currently Post and Page count show the same number
### What happened?

I cannot currently see an accurate count of how many posts and how many pages exist. Since they are the same model the count query returns the same exact results.

### How to reproduce the bug

When I create 1 post and 1 page, both counts say 2. When I add a second post, both counts say 3.

### Package Version

3.X

### PHP Version

8.1

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

When I create 1 post and 1 page, I want both to say 1. When I add a second post, I want posts to say 2 and pages to say 1.

### PR DESCRIPTION
**Pull request by mallardduck**
Per this title and the bug, this fixes the posts/pages counts being wrong.

Before the fix:
Screenshot 2024-03-05 at 2 37 46 PM
Screenshot 2024-03-05 at 2 38 02 PM

After the fix:
Screenshot 2024-03-05 at 2 38 24 PM
Screenshot 2024-03-05 at 2 38 16 PM

### CODE REVIEW

File: src/Filament/Resources/PageResource.php [hunk 1]
```diff
@@ -216,6 +216,11 @@ public static function getNavigationLabel(): string
         return __('Pages');
     }
 
+    public static function getNavigationBadge(): ?string
+    {
+        return (string) static::getEloquentQuery()->page()->count();
```
Comment (mallardduck) [inline src/Filament/Resources/PageResource.php]: One nit-pick - the current `page` and `posts` scopes will also scope based on `published_at` `<=` now. Which is probably a great default for 80% of times you want to scope these.

However, in the backend of the system you may not want that applied as that will exclude items to be posted in the future. And in the context of the filament panel badge number it may be best to have the "real" total of posts/pages, even ones to be published in the future included in that total.

**Comment by atmonshi** [comment]
thank you for the PR.
I agree with your point, I separate the published_at from the page and posts scope.

now should be all good

thank you again.

**Comment by mallardduck** [comment]
appreciate the fast response and merge. i'll def send more issues/PRs your way as I come across things while using sky to build the blog part of my website.
